source 'https://github.com/CocoaPods/Specs'

xcodeproj 'digiBridgeLocation Tests'
workspace '../digiBridgeLocation'
inhibit_all_warnings!

def import_pods
  pod 'digiBridgeLocation', :path => '../'
end

target :ios do
  platform :ios, '8.0'
  link_with 'iOS Tests'
  import_pods
end
